language: node_js
node_js:
  - stable
before_script:
  - npm install -g yo
  - npm install -g generator-swiftserver
  - osName="linux"
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then osName="osx"; fi
script:
  - ./testGenerator.sh
after_success:
  - ./updateRepo.sh
